Finish refactoring scripts, remove imgur script

diff --git a/R_scripts/usr/local/bin/fls b/R_scripts/usr/local/bin/fls
--- a/R_scripts/usr/local/bin/fls
+++ b/R_scripts/usr/local/bin/fls
@@ -17,7 +17,7 @@
 if [ "$#" -eq 0 ]; then
     f=
     firstline=1
-    while read a; do
+    while read -r a; do
         [ $firstline -eq 1 ] || f="$f
 "
         f="$f$a"
@@ -38,9 +38,10 @@ if [ "$#" -eq 0 ]; then
 else
     # Validate input
     for f in "$@"; do
-        [ ! -f "$f" -a ! -d "$f"  -a ! -L "$f" ] \
-            && echo "Error: the input(s) must be a file, a symlink or a directory." \
-            && exit 1
+        [ ! -f "$f" ] && [ ! -d "$f" ] && [ ! -L "$f" ] && {
+            echo "Error: the input(s) must be a file, a symlink or a directory."
+            exit 1
+        }
     done
 fi
 
@@ -57,18 +58,18 @@ BC=7  # Border foreground
 f="$(realpath -s "$1")"
 
 # Decorative wrappers
-b () { printf "$(tput bold)$*$(tput sgr0)"; } # Bold
-h () { printf "$(tput setaf $HFG && tput setab $HBG)$*$(tput setaf 7 && tput setab 0)"; } # Header
-f () { printf "$(tput setaf $BC)$*$(tput setaf 7)"; } # Frame
+b () { printf "%s" "$(tput bold)$*$(tput sgr0)"; } # Bold
+h () { printf "%s" "$(tput setaf $HFG && tput setab $HBG)$*$(tput setaf 7 && tput setab 0)"; } # Header
+f () { printf "%s" "$(tput setaf $BC)$*$(tput setaf 7)"; } # Frame
 
 # If multiple paths, calculate just the total size
 if [ "$#" -gt 1 ]; then
     FCOUNT=0; DCOUNT=0
     for x in "$@"; do
-        [ -f "$x" ] && FCOUNT=$(expr $FCOUNT + 1) && continue
-        [ -d "$x" ] && DCOUNT=$(expr $DCOUNT + 1) && continue
+        [ -f "$x" ] && FCOUNT=$((FCOUNT + 1)) && continue
+        [ -d "$x" ] && DCOUNT=$((DCOUNT + 1)) && continue
     done
-    printf \
+    printf "%s" \
  " $(f ┏━)$(h " BULK INFORMATION ")$(f ━╍╍┅┉)
  $(f ┃)  $(b Item Count:) $#
  $(f ┃)       $(b Files:) $FCOUNT
@@ -104,7 +105,7 @@ if [ -L "$f" ]; then
 
     handle_mime "$f"
 
- printf \
+ printf "%s" \
  " $(f ┏━)$(h " SYMLINK INFORMATION ")$(f ━╍╍┅┉)
  $(f ┃)    $(b Location:) '$f'
  $(f ┃)        $(b Type:) $TYPE
@@ -120,8 +121,11 @@ if [ -L "$f" ]; then
  $(f ┃)     $(b Created:) $(stat -c '%w' "$f" | sed 's/\..*//')
  $(f ┗━━━━━━━━━━$([ "$TYPE" != "SymLink (orphaned)" ] && echo ┳ || echo ━)━━━━━━━━━━━╍╍┅┉)
 "
-[ -f "$TARGET" -o -d "$TARGET" ] && echo "            $(f ┃)" && "$0" "$(readlink -f "$f")" | sed '1s/\(FILE\|DIRECTORY\)/TARGET/ ; $s/━/━━━/'
-exit 0
+    [ -f "$TARGET" ] || [ -d "$TARGET" ] && {
+        echo "            $(f ┃)"
+        "$0" "$(readlink -f "$f")" | sed '1s/\(FILE\|DIRECTORY\)/TARGET/ ; $s/━/━━━/'
+    }
+    exit 0
 
 # Handle file
 elif [ -f "$f" ]; then
@@ -129,7 +133,7 @@ elif [ -f "$f" ]; then
     BC=2
     handle_mime "$f"
 
- printf \
+ printf "%s" \
  " $(f ┏━)$(h " FILE INFORMATION ")$(f ━╍╍┅┉)
  $(f ┃)    $(b Location:) '$f'
  $(f ┃)        $(b Type:) File
@@ -152,12 +156,12 @@ else
     BC=4
     handle_mime "$f"
 
- printf \
+ printf "%s" \
  " $(f ┏━)$(h " DIRECTORY INFORMATION ")$(f ━╍╍┅┉)
  $(f ┃)    $(b Location:) '$f'
  $(f ┃)        $(b Type:) Directory
  $(f ┃)  $(b Total Size:) $(du -sh "$f" 2>&- | awk '{ print $1 }')
- $(f ┃)  $(b Item Count:) $(ls -A "$f" | wc -l)
+ $(f ┃)  $(b Item Count:) $(($(find "$f" -maxdepth 1 | wc -l)-1))
  $(f ┃)   $(b MIME Type:) $MIME
  $(f ┃)   $(b Opened By:) $OPENEDBY
  $(f ┃) $(b Owner/Group:) $(stat -c '%U/%G (%u/%g)' "$f")
