[scripts] Fix lxmake problem with input dir
The script would only work when the input file was in the current
working directory. Modified it to work from anywhere. Not battle-tested,
could have bugs.

diff --git a/scripts/.local/bin/lxmake b/scripts/.local/bin/lxmake
--- a/scripts/.local/bin/lxmake
+++ b/scripts/.local/bin/lxmake
@@ -49,8 +49,13 @@ if [ "$input" = - ]; then
     [ -z "$output" ] && output=-
     cat - >"$tinput"
 else
+    [ -n "$output" ] && [ "$output" != - ] && output="$(realpath -- "$output")"
+    inputdir="$(dirname -- "$input")"
+    cd -- "$inputdir" || { printf 'lxmake: failed to cd into "%s"' "$inputdir" >&2 && exit 9; }
+    input="$(basename -- "$input")"
     [ -z "$output" ] && output="${input%.*}.pdf"
     cp -- "$input" "$tinput"
+    unset inputdir
 fi
 unset input # no longer needed
 [ ! -s "$tinput" ] && echo 'lxmake: no input provided' >&2 && exit 2
