[scripts] Fix note script ledger support
Ledger has a kickass feature that lets it read GPG-encrypted journals.
Unfortunately, my note script stores notes as GPG-encrypted DIRECTORIES
of possibly many files. This is more flexible, but is not understood by
ledger. So, it was a bit of a pain and made the script uglier, but I
wrote in special ledger support that stores ledger notes as encrypted
files.
This means I can keep my finances encrypted along with the rest of my
notes, and simultaneously use ledger without hassle. Epic!

diff --git a/scripts/.local/bin/note b/scripts/.local/bin/note
--- a/scripts/.local/bin/note
+++ b/scripts/.local/bin/note
@@ -191,6 +191,29 @@ edit () {
     rm -rf -- "$tmpd"
 }
 
+# edit_ledger <file>
+# file - path to the note text file, relative to $notedir
+edit_ledger () {
+    [ ! -r "$gpgid" ] && echo "note: .gpg-id file not found, aborting." >&2 && exit 3
+    target="$(mktemp --tmpdir note.XXXXX."$(basename -- "$1")")"
+    gpg --yes --quiet --output "$target" --decrypt -- "$notedir/$1"
+
+    sum="$(sha1sum -- "$target")"
+    if [ -z "$interactive" ]; then
+        alacritty -e $EDITOR "+cd $tmpd" -- "$target"
+    else
+        $EDITOR "+cd $tmpd" -- "$target"
+    fi
+    if [ "$(sha1sum -- "$target")" = "$sum" ]; then
+        echo "No changes were made, skipping."
+    else
+        gpg --yes --quiet --output "$notedir/$1" --encrypt --recipient "$(cat -- "$gpgid")" -- "$target"
+        git -C "$notedir" add "$1"
+        git -C "$notedir" commit -o "$1" -m "Edit $1"
+    fi
+    rm -f -- "$target"
+}
+
 # view <archive>
 # archive - path to the note archive file, relative to $notedir
 view () {
@@ -250,6 +273,24 @@ view () {
     rm -rf -- "$tmpd"
 }
 
+# view_ledger <file>
+# file - path to the note text file, relative to $notedir
+view_ledger () {
+    target="$(mktemp --tmpdir note.XXXXX."$(basename -- "$1")")"
+    gpg --yes --quiet --output "$target" --decrypt -- "$notedir/$1"
+
+    # Perform string substitutions
+    strsub "$notedir/$1" "$target"
+
+    if [ -z "$interactive" ]; then
+        $TERMINAL -e $PAGER -- "$target"
+    else
+        $PAGER -- "$target"
+    fi
+
+    rm -f -- "$target"
+}
+
 # create <note> <ext>
 # note is a path of a new note relative to notedir
 # ext is the target NOTE file extension
@@ -288,13 +329,34 @@ create () {
     rm -rf -- "$tmpd"
 }
 
-# output <archive> <filename>
+# create_ledger <note>
+# note is a path of a new note relative to notedir
+create_ledger () {
+    [ ! -r "$gpgid" ] && echo "note: .gpg-id file not found, aborting." >&2 && exit 3
+    target="$(mktemp --tmpdir note.XXXXX."$(basename -- "$1")")"
+
+    if [ -z "$interactive" ]; then
+        alacritty -e $EDITOR "+cd ${TMPDIR:-/tmp}" -- "$target"
+    else
+        $EDITOR "+cd ${TMPDIR:-/tmp}" -- "$target"
+    fi
+    if [ ! -s "$target" ]; then
+        echo "Note unchanged, cancelling."
+    else
+        mkdir -p -- "$notedir/$(dirname -- "$1")"
+        gpg --yes --quiet --output "$notedir/$1" --encrypt --recipient "$(cat -- "$gpgid")" -- "$target"
+        git -C "$notedir" add "$1"
+        git -C "$notedir" commit -o "$1" -m "Create $1"
+    fi
+    rm -f -- "$target"
+}
+
+# output <archive> <output>
 # archive -  path to the note archive file, relative to $notedir
-# filename - path to the file to export to, or - for stdout
+# output - path to the file to export to, or - for stdout
 output () {
     [ -n "$raw" ] && {
         output="$2"
-        [ "$output" = - ] && echo 'note: cannot output to stdout when --raw is used' >&2 && exit 2
         [ -e "$output" ] && {
             [ ! -d "$output" ] && printf 'note: %s exists and is not a directory\n' "$output" >&2 && exit 1
             [ -n "$(ls -qA -- "$output")" ] && printf 'note: %s exists and is not empty\n' "$output" >&2 && exit 1
@@ -382,6 +444,34 @@ output () {
             printf "note: unknown note format \"%s\"\n" "$fmt" >&2
     esac
     rm -rf -- "$tmpd"
+}
+
+# output_ledger <file> <output>
+# file - path to the note text file, relative to $notedir
+# output - path to the file to export to, or - for stdout
+output_ledger () {
+    [ -n "$raw" ] && {
+        [ -e "$output" ] && printf 'note: %s exists\n' "$output" >&2 && exit 1
+        mkdir -p -- "$(dirname -- "$2")"
+        gpg --yes --quiet --output "$2" --decrypt -- "$notedir/$1"
+        return
+    }
+
+    target="$(mktemp --tmpdir note.XXXXX)"
+    gpg --yes --quiet --output "$target" --decrypt -- "$notedir/$1"
+    output="$2"
+    stdout=
+    [ "$output" = - ] && stdout=1
+
+    # Perform string substitutions
+    strsub "$notedir/$1" "$target"
+
+    if [ $stdout ]; then
+        cat -- "$target"
+    else
+        cp -- "$target" "$output"
+    fi
+    rm -f -- "$target"
 }
 
 note=
@@ -485,24 +575,47 @@ fi
 }
 
 # Execute the right action
-if [ -n "$output" ]; then
-    output "$note" "$output"
-elif [ -n "$edit" ]; then
-    if [ ! -f "$notedir/$note" ]; then
-        ext=
-        case "$note" in
-            *.md)   ext=.md   ;;
-            *.adoc) ext=.adoc ;;
-            *.txt)  ext=.txt  ;;
-            *.tex)  ext=.tex  ;;
-            *.typ)  ext=.typ  ;;
-            *.ldg)  ext=.ldg  ;;
-            *) echo 'note: missing or unsupported extension' >&2 && exit 2 ;;
-        esac
-        create "$note" "$ext"
-    else
-        edit "$note"
-    fi
-else
-    view "$note"
-fi
+#
+# All notes except ledger ones are encrypted directories consisting of a main
+# NOTE.ext file and optionally other files.
+# Ledger notes are simply encrypted text files, to cooperate with ledger's
+# GPGME support (https://passingcuriosity.com/2024/ledger-with-gnupg/). This
+# unfortunately means that they require separate handling from all other note
+# types.
+case "$note" in
+    *.ldg)
+        if [ -n "$output" ]; then
+            output_ledger "$note" "$output"
+        elif [ -n "$edit" ]; then
+            if [ ! -f "$notedir/$note" ]; then
+                create_ledger "$note"
+            else
+                edit_ledger "$note"
+            fi
+        else
+            view_ledger "$note"
+        fi
+        ;;
+    *)
+        if [ -n "$output" ]; then
+            output "$note" "$output"
+        elif [ -n "$edit" ]; then
+            if [ ! -f "$notedir/$note" ]; then
+                ext=
+                case "$note" in
+                    *.md)   ext=.md   ;;
+                    *.adoc) ext=.adoc ;;
+                    *.txt)  ext=.txt  ;;
+                    *.tex)  ext=.tex  ;;
+                    *.typ)  ext=.typ  ;;
+                    *) echo 'note: missing or unsupported extension' >&2 && exit 2 ;;
+                esac
+                create "$note" "$ext"
+            else
+                edit "$note"
+            fi
+        else
+            view "$note"
+        fi
+        ;;
+esac
