[scripts] Simplify plcategorize
Removed automatic group detection in favor of parsing the mappings file
as-is. Removed automatic finding of playlists in favor of trusting the
mappings file.
KiSS principle + more stability due to the reliability of the config
file.

diff --git a/scripts/.local/bin/plcategorize b/scripts/.local/bin/plcategorize
--- a/scripts/.local/bin/plcategorize
+++ b/scripts/.local/bin/plcategorize
@@ -8,11 +8,10 @@
 # - rg (ripgrep)
 # - taptempo (https://taptempo.tuxfamily.org)
 # - id3ted
-# - awk
 
 musicdir=~/Music
 pldir="$musicdir"/Playlists
-mappings="${XDG_CONFIG_HOME:-$HOME/.config}/plcategorize-mappings.tsv"
+mappings="${XDG_CONFIG_HOME:-$HOME/.config}/playlist-mappings.tsv"
 mpc_fmt='%file%%artist%%title%%album%%time%'
 tmp="$(mktemp -t plcategorize.XXXXX)" # aux buffer
 
@@ -22,12 +21,6 @@ cleanup () {
 }
 trap cleanup INT QUIT TERM EXIT
 
-[ ! -r "$mappings" ] && {
-    printf 'Failed to read %s.\n' "$mappings" >&2
-    exit 1
-}
-
-playlists="$(find "$pldir" -maxdepth 1 -type f -regex '.*/[_!@#%][^/]*\.m3u' -writable \! -name '#Fair Use.m3u' -exec basename -- '{}' \; | sort -k1.1,1.1r)"
 last_termw=
 last_change=
 
@@ -38,6 +31,22 @@ eprint () {
     printf "$@" >&2
     tput sgr0 >&2
 }
+
+# Read playlist mappings
+[ ! -r "$mappings" ] && {
+    printf 'Failed to read %s.\n' "$mappings" >&2
+    exit 1
+}
+playlists=
+while read -r line; do
+    [ -z "$line" ] && playlists="$playlists
+" && continue
+    fname="${line%%	*}"
+    prefix="${line##*	}"
+    [ ! -f "$pldir/$fname.m3u" ] && eprint 'Playlist not found: %s\n' "$fname" && exit
+    playlists="$playlists
+$fname.m3u"
+done <"$mappings"
 
 # Detect mapping collisions
 duplicates="$(cut -d'	' -f2 -- "$mappings" | sort | uniq -d)"
@@ -66,7 +75,7 @@ main () {
         # Print track information
         if [ -z "$file" ]; then
             tput sgr0
-            printf '  Nothing is selected, press return to refresh.\n'
+            printf '  Nothing is selected, press return to refresh.\n> '
             return 1
         else
             tput sgr0 bold
@@ -260,20 +269,18 @@ main () {
 
     # Print playlists state
     i=0
-    lastgroup=
     :>"$tmp"
     echo "$playlists" | while read -r plname; do
-        plfile="$pldir/$plname"
-        prefix="$(getprefix "${plname%.m3u}")"
-        group="${plname%"${plname#?}"}"
-        [ -z "$prefix" ] && eprint 'Missing prefix for playlist "%s"\n' "$plname"
-        [ "$group" != "$lastgroup" ] && {
+        [ -z "$plname" ] && {
             cat -- "$tmp"
             :>"$tmp"
             if [ $i -eq 0 ]; then printf '\n'; else printf '\n\n'; fi
-            lastgroup="$group"
             i=0
+            continue
         }
+        plfile="$pldir/$plname"
+        prefix="$(getprefix "${plname%.m3u}")"
+        [ -z "$prefix" ] && eprint 'Missing prefix for playlist "%s"\n' "$plname"
         tput bold setaf 4 >>"$tmp"
         printf '  %s ' "$prefix" >>"$tmp"
         if rg -Fq -- "$file" "$plfile"; then
@@ -283,7 +290,7 @@ main () {
         fi
         printf "%-${entryw}s" "${plname%.m3u}" >>"$tmp"
         i=$((i + 1))
-        [ "$((i % entrycols))" -eq 0 ] || [ "$group" != "$lastgroup" ] && {
+        [ "$((i % entrycols))" -eq 0 ] && {
             cat -- "$tmp"
             :>"$tmp"
             printf '\n'
