[scripts] Revamp plfilter script
The interface is copied from plcategorize. It is now possible to create
a custom selection of green and red playlists, and the final result will
include songs which belong to all the green ones and none of the red
ones.
The script speed has increased dramatically by using lua for hashsets.

diff --git a/scripts/.local/bin/plfilter b/scripts/.local/bin/plfilter
--- a/scripts/.local/bin/plfilter
+++ b/scripts/.local/bin/plfilter
@@ -1,45 +1,230 @@
-#!/usr/bin/sh
+#!/bin/sh
 
-# This script intakes multiple playlist names and returns a list of
-# files that are present on all the supplied playlists.
-# It then saves the filtered results in the ".Filtered.m3u" playlist.
+# Filter songs based on occurrence in playlists, interactive.
+#
+# Dependencies:
+# - mpd, mpc
+# - rg (ripgrep)
+# - lua
 
-playlistsdir=~/Music/Playlists
+musicdir=~/Music
+pldir="$musicdir"/Playlists
+plout="$pldir/.Filtered.m3u"
+mappings="${XDG_CONFIG_HOME:-$HOME/.config}/playlist-mappings.tsv"
+mpc_fmt='%file%%artist%%title%%album%%time%'
+setting="$(mktemp -t plfilter.XXXXX)"
+tmp="$(mktemp -t plfilter.XXXXX)" # aux buffer
+lua_script='
+hashset = {}
+isfirst = true
+for playlist in io.lines(arg[1]) do
+    if isfirst then
+        if playlist:sub(1, 1) == "+" then
+            for song in io.lines(playlist:sub(2)) do
+                hashset[song] = true
+            end
+        else
+            os.exit()
+        end
+        isfirst = false
+    else
+        if playlist:sub(1, 1) == "+" then
+            local to_unify = {}
+            for song in io.lines(playlist:sub(2)) do
+                to_unify[song] = true
+            end
+            for k, _ in pairs(hashset) do
+                if not to_unify[k] then
+                    hashset[k] = nil
+                end
+            end
+        elseif playlist:sub(1, 1) == "-" then
+            for song in io.lines(playlist:sub(2)) do
+                hashset[song] = nil
+            end
+        end
+    end
+end
+for k, _ in pairs(hashset) do
+    print(k)
+end
+'
 
-# If no args, print available playlists
-if [ "$#" = 0 ]; then
-    echo "Available playlists:"
-    find "$playlistsdir" -maxdepth 1 -type f -name "*.m3u" | while read -r line; do
-        printf -- "- %s\n" "$(basename -- "$line" ".m3u")"
+cleanup () {
+    rm -f -- "$tmp" "$setting"
+    exit 0
+}
+trap cleanup INT QUIT TERM EXIT
+
+last_termw=
+last_change=
+
+eprint () {
+    tput sgr0 >&2
+    printf '  ' >&2
+    tput setaf 15 setab 1 >&2
+    printf "$@" >&2
+    tput sgr0 >&2
+}
+
+# Read playlist mappings
+[ ! -r "$mappings" ] && {
+    printf 'Failed to read %s.\n' "$mappings" >&2
+    exit 1
+}
+playlists=
+while read -r line; do
+    [ -z "$line" ] && playlists="$playlists
+" && continue
+    fname="${line%%	*}"
+    prefix="${line##*	}"
+    [ ! -f "$pldir/$fname.m3u" ] && eprint 'Playlist not found: %s\n' "$fname" && exit
+    playlists="$playlists
+$fname.m3u"
+done <"$mappings"
+
+# Detect mapping collisions
+duplicates="$(cut -d'	' -f2 -- "$mappings" | sort | uniq -d)"
+[ -n "$duplicates" ] && {
+    eprint "Prefix collisions: "
+    for dupe in ${duplicates% *}; do
+        eprint "$dupe"
     done
-    exit
-fi
+    eprint '\n'
+    exit 2
+}
 
-# Validate input
-for arg in "$@"; do
-    [ ! -f "$playlistsdir/$arg.m3u" ] && printf "plfilter: playlist \"%s\" not found\n" "$arg" >&2 && exit 1
+getprefix () {
+    match="$(rg -F -- "$1	" "$mappings")"
+    echo "${match##*	}"
+}
+
+getplaylist () {
+    match="$(cut -d'	' -f2 -- "$mappings" | rg -Fn -- "$1")"
+    [ -z "$match" ] && return
+    sed -n "${match%%:*}s/	.*//p" "$mappings"
+}
+
+main () {
+    # Parse menu inputs
+    [ "$1" = q ] && echo Bye. && exit
+    [ "$1" =  ] && {
+        echo "$lua_script" | lua - "$setting" >"$plout"
+        set -- ''
+    }
+
+    # Print header
+    clear
+    tput setab 15 setaf 0 bold
+    printf ' plfilter '
+    tput sgr0
+    printf ' %sq%s exit  '   "$(tput bold setaf 4)" "$(tput sgr0)"
+    printf '%sESC%s apply  ' "$(tput bold setaf 4)" "$(tput sgr0)"
+    nlines="$(wc -l -- "$plout")"
+    nlines="${nlines%% *}"
+    printf '%s(%s result%s)\n' "$(tput setaf 8)" "$nlines" "$([ "$nlines" -eq 1 ] || printf 's')"
+    tput sgr0
+
+    # Parse user input
+    [ -n "$1" ] && {
+        left="$1"
+        while [ -n "$left" ]; do
+            prefix="${left%"${left#?}"}"
+            left="${left#?}"
+            playlist="$(getplaylist "$prefix")"
+            [ -z "$playlist" ] && {
+                eprint 'Missing playlist for prefix: %s\n' "$prefix"
+                continue
+            }
+            plfile="$pldir/$playlist.m3u"
+            [ ! -f "$plfile" ] && {
+                eprint 'No such file: "%s"\n' "$plfile"
+                continue
+            }
+            line="$(rg -Fn -- "$plfile" "$setting")"
+            if [ -z "$line" ]; then
+                echo "+$plfile" >>"$setting"
+            else
+                [ "$(printf '%s' "$line" | wc -l)" -ne 0 ] && eprint 'More than one match for "%s"\n' "$plfile" && return
+                lineno="${line%%:*}"
+                state="${line#*:}"
+                state="${state%"${state#?}"}"
+                if [ "$state" = + ]; then
+                    sed -i "${lineno}s/^\+/-/" "$setting"
+                elif [ "$state" = - ]; then
+                    sed -i "${lineno}d" "$setting"
+                else
+                    eprint 'Invalid line in setting: "%s"\n' "$line"
+                fi
+            fi
+            sort -k1.1,1.1 -o "$setting" "$setting"
+        done
+    }
+
+    # Print last non-empty line input by user
+    [ -n "$1" ] && last_change="$1"
+    tput sgr0 setaf 7
+    printf '\n  %s\n' "$last_change"
+
+    # Recalculate column layout
+    termw="$(tput cols)"
+    [ "$termw" != "$last_termw" ] && {
+        printf 0 >"$tmp"
+        echo "$playlists" | while read -r plname; do
+            w="$(printf '%s' "${plname%.m3u}" | wc -m)"
+            [ "$w" -gt "$(cat -- "$tmp")" ] && printf '%s' "$w" >"$tmp"
+        done
+        entryw="$(cat -- "$tmp")"
+        entrycols="$(( (termw - 2) / (entryw + 4) ))"
+        [ "$entrycols" -lt 1 ] && entrycols=1
+        [ "$entrycols" -gt 4 ] && entrycols=4
+        last_termw="$termw"
+    }
+
+    # Print playlists state
+    i=0
+    :>"$tmp"
+    echo "$playlists" | while read -r plname; do
+        [ -z "$plname" ] && {
+            cat -- "$tmp"
+            :>"$tmp"
+            if [ $i -eq 0 ]; then printf '\n'; else printf '\n\n'; fi
+            i=0
+            continue
+        }
+        plfile="$pldir/$plname"
+        prefix="$(getprefix "${plname%.m3u}")"
+        [ -z "$prefix" ] && eprint 'Missing prefix for playlist "%s"\n' "$plname"
+        tput bold setaf 4 >>"$tmp"
+        printf '  %s ' "$prefix" >>"$tmp"
+        if rg -Fq -- "+$plfile" "$setting"; then
+            tput setaf 10 >>"$tmp"
+        elif rg -Fq -- "-$plfile" "$setting"; then
+            tput setaf 9 >>"$tmp"
+        else
+            tput sgr0 setaf 7 >>"$tmp"
+        fi
+        printf "%-${entryw}s" "${plname%.m3u}" >>"$tmp"
+        i=$((i + 1))
+        [ "$((i % entrycols))" -eq 0 ] && {
+            cat -- "$tmp"
+            :>"$tmp"
+            printf '\n'
+            i=0
+        }
+    done
+    [ -s "$tmp" ] && {
+        cat -- "$tmp"
+        printf '\n'
+    }
+
+    # Show prompt
+    tput sgr0
+    printf '\n> '
+}
+
+data=
+main
+while read -r line; do
+    main "$line"
 done
-
-# Filter
-tmp="$(mktemp -p /tmp plfilter.XXXXX)"
-cp -- "$playlistsdir/$1.m3u" "$tmp"
-skipfirst=
-for arg in "$@"; do
-    [ -z "$skipfirst" ] && skipfirst=1 && continue
-
-    pl="$playlistsdir/$arg.m3u"
-    while read -r line; do
-        query="$(printf "%s" "$line" | sed -e 's/\//\\\//g' -e 's/\[/\\\[/g' -e 's/\]/\\\]/g' -e 's/\./\\\./g')"
-        # prepend every matching line with '#'
-        sed -i "/^#*$query\$/s/^/#/" "$tmp"
-    done <"$pl"
-done
-
-# Delete all lines without "$#" leading #'s, because they were not matched by all
-sed -ni "s/^#\{$(( $# - 1 ))\}//p" "$tmp"
-
-# Add filter bio comment on top
-sed -i "1i # filter: $*" "$tmp"
-
-mv -- "$tmp" "$playlistsdir/.Filtered.m3u"
-printf "%s filtered line(s)\n" "$(($(wc -l -- "$playlistsdir/.Filtered.m3u" | awk '{ print $1 }') - 1))"
