[scripts] Revamp regain script
Now allows for 3 modes: single (file), album (dir) and singles (dir),
much like the revamped normalize script.

diff --git a/scripts/.local/bin/regain b/scripts/.local/bin/regain
--- a/scripts/.local/bin/regain
+++ b/scripts/.local/bin/regain
@@ -1,11 +1,65 @@
 #!/bin/sh
 
-# Use mp3gain to force a recalculation of gain
-# in ID3v2 tags. If an update is recommended,
-# offer it to the user interactively.
+# Normalize a single file or directory with mp3gain.
+# Directories can be treated both as singles and as an album.
 
-mp3gain -s r -e "$@"
-printf "regain: Overwrite current tag information? [Y/n] "
-read -r ans
-[ -n "$ans" ] && [ "$ans" != Y ] && [ "$ans" != y ] && exit
-mp3gain -s r -r -e "$@"
+set -e
+
+usage () {
+    echo 'Usage:  regain [OPTION] [FILE]'
+    echo
+    echo 'Normalize an mp3 file or a directory of mp3 files.'
+    echo 'In case of a directory, it must be specified whether'
+    echo 'to normalize each track individually, or as an album.'
+    echo
+    echo 'Options:'
+    echo '-h: Print this help.'
+    echo '-a DIR: Analyze directory as an album.'
+    echo '-s DIR: Analyze directory as singles.'
+}
+
+if [ "$1" = '-h' ]; then
+    usage
+    exit
+elif [ "$#" -eq 1 ]; then
+    # Single file
+    [ -f "$1" ] || {
+        echo "regain: file path expected. Try '-h' for help." >&2
+        exit 1
+    }
+    tput setaf 4
+    printf 'Normalizing file '
+    tput bold setaf 3
+    printf '"%s"\n' "$1"
+    tput sgr0
+    mp3gain -s r -r -e -k "$1"
+elif [ "$#" -eq 2 ]; then
+    # Directory of files
+    [ -d "$2" ] || {
+        echo "regain: directory path expected. Try '-h' for help." >&2
+        exit 1
+    }
+    if [ "$1" = '-a' ]; then
+        tput setaf 4
+        printf 'Normalizing album '
+        tput bold setaf 3
+        printf '"%s"\n' "$2"
+        tput sgr0
+        find "$2" -maxdepth 1 -type f -name '*.mp3' -print0 \
+            | xargs -0 mp3gain -s r -a -k
+    elif [ "$1" = '-s' ]; then
+        tput setaf 4
+        printf 'Normalizing singles '
+        tput bold setaf 3
+        printf '"%s"\n' "$2"
+        tput sgr0
+        find "$2" -maxdepth 1 -type f -name '*.mp3' -print0 \
+            | xargs -0 mp3gain -s r -a -k
+    else
+        echo "regain: Invalid argument. Try '-h' for help." >&2
+        exit 1
+    fi
+else
+    echo "regain: Invalid number of arguments. Try '-h' for help." >&2
+    exit 1
+fi
