Allow empty WCOP frame in fairuse scripts
I forgot about this while writing them for the first time, but the WCOP
frame can be empty in cases of message approved music usage, odd
licenses or other.

diff --git a/scripts/.local/bin/scanfairuse b/scripts/.local/bin/scanfairuse
--- a/scripts/.local/bin/scanfairuse
+++ b/scripts/.local/bin/scanfairuse
@@ -17,21 +17,23 @@ artists="$HOME/Music/Playlists/artists.yaml"
 
 while read -r relative <&3; do
     f="$base/$relative"
-    [ ! -f "$f" ] && echo "Invalid path \"$f\" detected, run plfix." >&2 && exit 1
+    [ ! -f "$f" ] && echo "invalid path \"$f\" detected, run plfix." >&2 && exit 1
 
     frames="$(id3ted -l -- "$f")"
     artist="$(printf "%s" "$frames" | sed -n "s/^TPE1: //p")"
+    license="$(printf "%s" "$frames" | sed -n "s/^TCOP: //p")"
 
     if  [ -z "$artist" ] || \
+        [ -z "$license" ] || \
         ! printf "%s" "$frames" | grep -q "^TIT2: " || \
-        ! printf "%s" "$frames" | grep -q "^TCOP: " || \
         ! printf "%s" "$frames" | grep -q "^COMM: \[license\]" || \
-        ! printf "%s" "$frames" | grep -q "^WCOP: " || \
         ! printf "%s" "$frames" | grep -q "^WXXX: \[origin\]";
     then
-        printf "Tags missing from '%s', running addfairuse...\n" "$relative"
+        printf "tags missing from '%s', running addfairuse...\n" "$relative"
         sleep 1
         addfairuse "$f"
+    elif ! printf "%s" "$frames" | grep -q "^WCOP: "; then
+        printf "warning: license '%s' has no URL (%s)\n" "$license" "$relative"
     elif ! grep -qF "artist: $artist" "$artists"; then
         printf "'%s' not found in artists.yaml\n" "$artist"
     fi
