Reformat dotmerge script to be POSIX compliant
Also changed vimdiff to nvim -d, because that's how neovim handles it.

diff --git a/H_scripts/.local/bin/dotmerge b/H_scripts/.local/bin/dotmerge
--- a/H_scripts/.local/bin/dotmerge
+++ b/H_scripts/.local/bin/dotmerge
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 # Intakes a git branch name and a file inside a stow-managed dotfiles folder, and automatically opens a vimdiff session with both files,
 # after a closed edit it makes all the necessary replacements to place the diffed file inside the dotfiles directory.
@@ -7,23 +7,30 @@ BRANCH="$1"
 FILEPATH="$2"
 
 # Check if git branch exists
-if [[ -z $(git rev-parse --verify --quiet $BRANCH) ]]; then echo "Error: no git branch named '$1' inside this directory."; exit; fi
+if [ -z "$(git rev-parse --verify --quiet "$BRANCH")" ]; then
+    printf "Error: no git branch named '%s' inside this directory.\n" "$1"
+    exit 1
+fi
 
 # Check if file exists
-if [[ ! -f $FILEPATH ]]; then echo "Error: no file named '$2' was found."; exit; fi
-FILENAME="$(basename $2)"
+if [ ! -f "$FILEPATH" ]; then
+    echo "Error: no file named '$2' was found."
+    exit 1
+fi
+
+FILENAME="$(basename -- "$2")"
 
 # Create a safe directory to process files
 DIR="$HOME/.cache/dotmerge"
-mkdir -p $DIR
+mkdir -p -- "$DIR"
 
-cp $FILEPATH "$DIR/$FILENAME"
-git checkout $BRANCH -- $FILEPATH
-mv $FILEPATH "$DIR/$FILENAME.$BRANCH"
+cp -- "$FILEPATH" "$DIR/$FILENAME"
+git checkout "$BRANCH" -- "$FILEPATH"
+mv -- "$FILEPATH" "$DIR/$FILENAME.$BRANCH"
 
-vimdiff "$DIR/$FILENAME" "$DIR/$FILENAME.$BRANCH"
+nvim -d "$DIR/$FILENAME" "$DIR/$FILENAME.$BRANCH"
 wait
 
-mv "$DIR/$FILENAME" $FILEPATH
-rm "$DIR/$FILENAME.$BRANCH"
+mv -- "$DIR/$FILENAME" "$FILEPATH"
+rm -- "$DIR/$FILENAME.$BRANCH"
 
